### ISSUE TITLE
Query Arguments Are Not Quoted

### ISSUE THREAD

**Issue by sshaw** [skinnyjames/graphlyte#4]
require "graphlyte"
    
    query = Graphlyte.query do |q|
      q.collection(:id => "gid://shopify/Collection/555923539") do |q|
        q.updatedAt
      end
    end
    
    puts query.to_s

Results in: 

    {
      collection(id: gid://shopify/Collection/555923539){
        updatedAt  
      }
    }
    

~Not~ Note that `id`'s value is not quoted.

**Comment by skinnyjames** [comment]
Oh thanks! 
I'm a little newer to graphql, this helps alot.

**Comment by skinnyjames** [comment]
0.1.2 is released

**Comment by skinnyjames** [comment]
I might have to revisit this.  I'm looking at the spec now

**Comment by skinnyjames** [comment]
this is fixed
